<?php

/**
 * This file was automatically generated by Fusion.
 * You should not edit it.
 */
namespace Fusion\Generated\Pages;

class ActionGenerated extends \Fusion\FusionPage
{
    use \Fusion\Concerns\IsProceduralPage;
    public function runProceduralCode()
    {
        $this->expose(getHeader: fn() => request()->header('User-Agent'));
        $this->syncProps(get_defined_vars());
    }
    #[\Fusion\Attributes\Expose]
    public function getHeader()
    {
        return call_user_func($this->actions[__FUNCTION__], ...func_get_args());
    }
}