<?php

/**
 * This file was automatically generated by Fusion.
 * You should not edit it.
 */
namespace Fusion\Generated\Pages;

class CounterGenerated extends \Fusion\FusionPage
{
    #[\Fusion\Attributes\ServerOnly]
    public array $discoveredProps = ['count', 'doubleCount'];
    use \Fusion\Concerns\IsProceduralPage;
    public function runProceduralCode()
    {
        $count = $this->prop(name: 'count', default: 0)->value();
        $doubleCount = $this->prop(name: 'doubleCount', default: fn() => $count * 2)->readonly()->value();
        $this->syncProps(get_defined_vars());
    }
}